version: "3"

services:

  # PHP FPM
  php-fpm:
    build: './.docker/php-fpm'
    container_name: news-portal_php-fpm
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app

  # Nginx
  nginx:
    image: nginx:1.15
    container_name: news-portal_nginx
    volumes:
      - ./:/var/www/app
      - ./.docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/app
    ports:
      - 8080:80
    depends_on:
      - php-fpm

  # MySQL
  mysql:
    image: mysql:5.7
    container_name: news-portal_mysql
    volumes:
      - ./var/mysql:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=news_portal_local
      - MYSQL_ROOT_PASSWORD=root

